-- ============================================================
-- WORLD CHOICE PERFUMES — info@ mailbox (Customer Care → Mails)
-- Run this in the Supabase SQL Editor ONCE.
--
-- What it does:
--   * `info_emails` — every email delivered to info@worldchoiceperfume.com.
--     Cloudflare Email Routing hands the raw RFC 822 message to the app at
--     POST /api/inbound-emails (see app/Http/Controllers/Api/InfoMailWebhookController.php)
--     and the parsed parts are stored here, so Customer Care can read the mail,
--     mark it, and answer it as info@ without anyone touching a mailbox.
--   * `info_email_replies` — the answers sent back out. The Message-ID of each
--     sent reply is recorded, so when the customer hits reply their next
--     email (which carries `In-Reply-To: <that id>`) is filed into the same
--     thread instead of starting a new one.
--
-- Columns that only exist for the reader's convenience:
--   * body_text is the plain-text part (list previews, search).
--   * body_html is the HTML part, shown sandboxed on the mail page.
--   * raw_email keeps the untouched message so nothing is ever lost.
--   * attachment_names records what came in; the bytes are not stored.
--
-- Safe to run more than once.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.info_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Message-ID of the incoming mail. Doubles as the de-duplication key:
    -- a re-delivered mail is ignored instead of listed twice.
    message_id TEXT,
    in_reply_to TEXT,
    -- Named reference_ids rather than "references" so the column can never
    -- collide with the SQL keyword. The value is the raw References header.
    reference_ids TEXT,
    from_email TEXT NOT NULL,
    from_name TEXT,
    to_email TEXT,
    cc TEXT,
    bcc TEXT,
    reply_to TEXT,
    subject TEXT,
    body_text TEXT,
    body_html TEXT,
    raw_email TEXT,
    headers JSONB,
    attachment_names TEXT,
    has_attachments BOOLEAN NOT NULL DEFAULT false,
    -- Cloudflare adds these as Authentication-Results; kept so staff can
    -- see whether a message really came from the address it claims.
    spf_result TEXT,
    dkim_result TEXT,
    is_read BOOLEAN NOT NULL DEFAULT false,
    is_starred BOOLEAN NOT NULL DEFAULT false,
    -- new → a mail nobody has answered yet, replied → we answered it,
    -- closed → dealt with, no answer needed.
    status TEXT NOT NULL DEFAULT 'new',
    -- Root of the conversation. Equal to this row's own message_id for a new
    -- mail, and to the original mail's thread_key for a follow-up, so the
    -- whole conversation can be read back in order.
    thread_key TEXT,
    parent_id BIGINT REFERENCES public.info_emails(id) ON DELETE SET NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    read_at TIMESTAMPTZ,
    replied_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_info_emails_message_id
    ON public.info_emails (message_id)
    WHERE message_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_info_emails_thread_key
    ON public.info_emails (thread_key);

CREATE INDEX IF NOT EXISTS idx_info_emails_received_at
    ON public.info_emails (received_at DESC);

CREATE TABLE IF NOT EXISTS public.info_email_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    info_email_id BIGINT NOT NULL REFERENCES public.info_emails(id) ON DELETE CASCADE,
    from_email TEXT NOT NULL,
    to_email TEXT NOT NULL,
    subject TEXT,
    body TEXT NOT NULL,
    -- Message-ID of the mail we sent. Matched against the next email's
    -- In-Reply-To header to keep the conversation together.
    message_id TEXT,
    in_reply_to TEXT,
    -- sent → handed to the mail provider, failed → the provider refused it
    -- and the answer was never delivered.
    status TEXT NOT NULL DEFAULT 'sent',
    error TEXT,
    sent_by BIGINT,
    sent_by_name TEXT,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_info_email_replies_email
    ON public.info_email_replies (info_email_id);

CREATE INDEX IF NOT EXISTS idx_info_email_replies_message_id
    ON public.info_email_replies (message_id)
    WHERE message_id IS NOT NULL;

NOTIFY pgrst, 'reload schema';
