-- ============================================================
-- WORLD CHOICE PERFUMES — Branch Stock Transfers
-- Run this in the Supabase SQL Editor ONCE before enabling the
-- stock transfer feature in the Stock Manager UI.
--
-- Summary:
--   * `stock_transfers`           — header of a transfer between two
--     branches (status in_transit / received).
--   * `stock_transfer_items`      — the individual items moved with a
--     transfer. Items still in the "transfer stock" are those with
--     status = 'in_transit' (not yet received by the target branch).
--   * Extends the `stock_movement_type` enum with 'transfer_out' and
--     'transfer_in' so product stock movements show a dedicated type.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.stock_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_number TEXT NOT NULL UNIQUE,
    stock_type TEXT NOT NULL CHECK (stock_type IN ('product', 'bottle', 'oil_fragrance', 'bottle_accessories')),
    from_branch_id BIGINT NOT NULL REFERENCES public.branches(id) ON DELETE RESTRICT,
    to_branch_id BIGINT NOT NULL REFERENCES public.branches(id) ON DELETE RESTRICT,
    status TEXT NOT NULL DEFAULT 'in_transit' CHECK (status IN ('in_transit', 'received')),
    note TEXT,
    officer_name TEXT,
    officer_phone TEXT,
    officer_id TEXT,
    created_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    received_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    received_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.stock_transfer_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id BIGINT NOT NULL REFERENCES public.stock_transfers(id) ON DELETE CASCADE,
    stock_type TEXT NOT NULL CHECK (stock_type IN ('product', 'bottle', 'oil_fragrance', 'bottle_accessories')),
    item_index INTEGER NOT NULL DEFAULT 0,
    product_id BIGINT REFERENCES public.products(id) ON DELETE RESTRICT,
    name TEXT,
    volume TEXT,
    variant TEXT,
    type TEXT,
    color TEXT,
    quantity INTEGER NOT NULL DEFAULT 0,
    unit_cost NUMERIC(12, 2),
    unit_price NUMERIC(12, 2),
    category TEXT,
    supplier TEXT,
    status TEXT NOT NULL DEFAULT 'in_transit' CHECK (status IN ('in_transit', 'received')),
    received_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    received_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Dedicated movement types for product stock transfers. Run these even if
-- the stock_movement_type enum was already built without them.
ALTER TYPE public.stock_movement_type ADD VALUE IF NOT EXISTS 'transfer_out';
ALTER TYPE public.stock_movement_type ADD VALUE IF NOT EXISTS 'transfer_in';

CREATE INDEX IF NOT EXISTS idx_stock_transfers_to ON public.stock_transfers (to_branch_id, status);
CREATE INDEX IF NOT EXISTS idx_stock_transfers_from ON public.stock_transfers (from_branch_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_items_transfer ON public.stock_transfer_items (transfer_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_items_status ON public.stock_transfer_items (transfer_id, status);

NOTIFY pgrst, 'reload schema';