-- ============================================================
-- WORLD CHOICE PERFUMES — Per-product bottle variety stock
-- Run this in the Supabase SQL Editor ONCE.
--
-- Problem this solves:
--   Product stock-in for Oil Fragrance products records a quantity
--   and the bottle volume/variety (box / logo / color) used to bottle
--   it, but branch_stock only holds a single per-product quantity.
--   Transfers (and stock-outs) therefore could not know how many
--   units of a specific product exist in a specific bottling — e.g.
--   "how many Test perfume 50ml With Box · With Logo · Yellow".
--
-- Summary:
--   * `branch_stock_varieties` — quantity per
--     (branch_id, product_id, volume, variety). A row is written at
--     product stock-in for oil fragrance products (bottle_volume +
--     bottle_variant inputs) and adjusted by stock transfers.
--   * Stock-in inserts/increments the matching row; transfer out
--     decrements it; transfer in (receiving branch) increments it.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.branch_stock_varieties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    volume INTEGER NOT NULL,
    variant TEXT NOT NULL DEFAULT 'plain',
    quantity INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (branch_id, product_id, volume, variant)
);

CREATE INDEX IF NOT EXISTS idx_branch_stock_varieties_branch_product
    ON public.branch_stock_varieties (branch_id, product_id);

NOTIFY pgrst, 'reload schema';
